//
//  MainPresenter.swift
//  WeatherTestApp
//
//  Created by Aleksandr Kretov on 06.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentWeather(response: MainScene.LoadWeather.Response)
    func presentError(response: MainScene.HandleError.Response)
    func presentSearchResults(response: MainScene.SearchCities.Response)
}

final class MainPresenter: MainPresentationLogic {

    // MARK: - Public Properties

    weak var viewController: MainDisplayLogic?

    // MARK: - Presentation Logic

    func presentWeather(response: MainScene.LoadWeather.Response) {
        let cellsViewModels = response.weather.map { daily in
            let icon = getWeatherIcon(from: daily.list.first?.weather.first?.icon)
            return WeatherCellViewModel(cityName: daily.city.name ?? "noname",
                                        weatherIcon: icon,
                                        temp: getFormattedTemp(daily.list.first?.main.temp ?? 0),
                                        currentTime: formatGMTDate(from: daily.city.timezone ?? 0),
                                        cityId: daily.city.id ?? 0)
        }
        let viewModel = MainScene.LoadWeather.ViewModel(weatherCellViewModels: cellsViewModels, placeCellViewModels: [])
        viewController?.displayCurrentWeather(viewModel: viewModel)
    }

    func presentSearchResults(response: MainScene.SearchCities.Response) {
        let cellsViewModels = response.filteredForecast.map { daily in
            let icon = UIImage(named: String(daily.list.first?.weather.first?.icon?.dropLast() ?? ""))
            return WeatherCellViewModel(cityName: daily.city.name ?? "noname",
                                        weatherIcon: icon,
                                        temp: getFormattedTemp(daily.list.first?.main.temp ?? 0),
                                        currentTime: formatGMTDate(from: daily.city.timezone ?? 0),
                                        cityId: daily.city.id ?? 0)
        }

        let placesViewModels = response.places.map { PlaceCellViewModel(cityName: $0.name,
                                                                        stateName: $0.state,
                                                                        countryName: getCountryName(from: $0.country))}

        let viewModel = MainScene.LoadWeather.ViewModel(weatherCellViewModels: cellsViewModels, placeCellViewModels: placesViewModels)
        viewController?.displaySearchResults(viewModel: viewModel)
    }

    func presentError(response: MainScene.HandleError.Response) {
        let messege = response.error.asAFError?.localizedDescription
        let viewModel = MainScene.HandleError.ViewModel(errorMessage: messege ?? "")
        viewController?.displayError(viewModel: viewModel)
    }

    // MARK: - Private methods

    private func getCountryName(from countryCode: String) -> String {
        let currentLocale = Locale.current
        return currentLocale.localizedString(forRegionCode: countryCode) ?? countryCode
    }

    private func getWeatherIcon(from code: String?) -> UIImage? {
        guard
            let codePrefix = code?.prefix(2),
            let image = UIImage(named: String(codePrefix))
        else { return nil }
        return image
    }

    private func formatGMTDate(from seconds: Int) -> String {
        let date = Date()
        let timeZone = TimeZone(secondsFromGMT: seconds)
        let formatter = DateFormatter()
        formatter.timeZone = timeZone
        formatter.dateFormat = "HH:mm"
        return formatter.string(from: date)
    }

    private func getFormattedTemp(_ temp: Double) -> String {
        if round(temp) == 0 {
            // If temp is Zero ignore "-" sign and return 0
            return NSString(format: "0%@" as NSString, "\u{00B0}") as String
        } else {
            let roundedTemp = String(format: "%.f", temp)
            return NSString(format: "\(roundedTemp)%@" as NSString, "\u{00B0}") as String
        }
    }
}
