//
//  MainRouter.swift
//  WeatherTestApp
//
//  Created by Aleksandr Kretov on 06.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToDetailsVC()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

final class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {


    // MARK: - Public properties

    var dataStore: MainDataStore?
    weak var viewController: MainViewController?

    // MARK: - Routing Logic

    func routeToDetailsVC() {
        let destination = DetailsViewController()
        guard
            let source = viewController,
            var destinationDS = destination.router?.dataStore,
            let dataStore
        else {
            return
        }

        passData(source: dataStore, destination: &destinationDS)
        navigate(source: source, destination: destination)
    }

    // MARK: - Private methods
    
    private func navigate(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }

    private func passData(source: MainDataStore, destination: inout DetailsDataStore) {
        guard let viewController else { return }
        let indexPath = viewController.tableView.indexPathForSelectedRow
        if let indexPath {
            if viewController.isSearching {
                destination.weather = source.filteredWeather[indexPath.row]
            } else {
                destination.weather = source.currentWeather[indexPath.row]
            }
        }
    }
}
