//
//  DetailsModels.swift
//  WeatherTestApp
//
//  Created by Aleksandr Kretov on 10.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Details {
    // MARK: Use cases

    enum ShowForecast {

        struct Response {
            let forecast: DailyForecast
        }

        struct ViewModel {
            let headerViewModel: TopHeaderViewModelProtocol
            let hourlyForecastViewModels: [HourlyCellViewModelProtocol]
            let dailyForecastViewModels: [DayForecastViewModelProtocol]
            let miscInfoViewModel: MiscInfoViewModelProtocol
        }
    }

    enum HandleError {
        struct Response {
            let error: Error
        }

        struct ViewModel {
            let errorMessage: String
        }
    }
}

struct HeaderViewModel: TopHeaderViewModelProtocol {
    var cityName: String
    var temp: String
    var conditionDescription: String
    var hiTemp: String
    var lowTemp: String
    var shorInfo: String {
        "\(temp) | \(conditionDescription)"
    }
}

struct HourlyCellViewModel: HourlyCellViewModelProtocol {
    var timeTitle: String
    var iconName: String
    var tempTitle: String
}

struct DayForecastViewModel: DayForecastViewModelProtocol {
    var dayName: String
    var iconName: String
    var precipitationTitle: String?
    var dayTemp: String
    var nightTemp: String
}

struct MiscInfoViewModel: MiscInfoViewModelProtocol {
    var weatherDescription: String
    var sunriseTime: String
    var sunsetTime: String
    var chanceOfPop: String?
    var chanceOfSnow: String?
    var humidity: String
    var wind: String
    var feelsLike: String
    var precipitation: String
    var pressure: String
    var visibility: String
    var uvIndex: String
    var isRain: Bool
}

