//
//  DetailsViewController.swift
//  WeatherTestApp
//
//  Created by Aleksandr Kretov on 10.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol DetailsDisplayLogic: AnyObject {
    func displayDetailedForecast(viewModel: Details.ShowForecast.ViewModel)
    func displayCurrentWeather(viewModel: Details.ShowCurrentWeather.ViewModel)
}

final class DetailsViewController: UIViewController, DetailsDisplayLogic {

    // MARK: - Public properties

    var interactor: DetailsBusinessLogic?
    var router: (NSObjectProtocol & DetailsRoutingLogic & DetailsDataPassing)?

    // MARK: Views

    private lazy var scrollView: UIScrollView = {
        let scrollView = UIScrollView()
        scrollView.translatesAutoresizingMaskIntoConstraints = false
        scrollView.alwaysBounceVertical = true
        scrollView.delegate = topHeaderView
        scrollView.alpha = 0
        return scrollView
    }()

    private lazy var topHeaderView = TopHeaderView(frame: CGRect(x: 0,
                                                                 y: statusBarHeight,
                                                                 width: view.frame.width,
                                                                 height: 326))

    private lazy var dayForecastStack = DayForecastStackView()


    private let collectionView = HourlyForecastCollectionView()

    private let miscInfoView = MiscInfoView()

    private let firstSeparator = makeSeparator()

    private let secondSeparator = makeSeparator()

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    // MARK: - Setup Clean Code Design Pattern

    private func setup() {
        let viewController = self
        let networkService = AFNetworkService()
        let interactor = DetailsInteractor(networkService: networkService)
        let presenter = DetailsPresenter()
        let router = DetailsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    private func setupConstraints() {

        view.addSubview(firstSeparator)
        view.addSubview(secondSeparator)

        view.addSubview(topHeaderView)
        view.addSubview(collectionView)
        view.addSubview(scrollView)
        scrollView.addSubview(dayForecastStack)
        scrollView.addSubview(miscInfoView)

        firstSeparator.snp.makeConstraints { make in
            make.width.equalToSuperview()
            make.height.equalTo(0.5)
            make.top.equalTo(topHeaderView.snp.bottom)
        }

        collectionView.snp.makeConstraints { make in
            make.top.equalTo(firstSeparator.snp.bottom)
            make.width.equalToSuperview()
            make.height.equalTo(116)
        }

        secondSeparator.snp.makeConstraints { make in
            make.top.equalTo(collectionView.snp.bottom)
            make.width.equalToSuperview()
            make.height.equalTo(0.5)
        }

        scrollView.snp.makeConstraints { make in
            make.top.equalTo(secondSeparator.snp.bottom)
            make.width.equalToSuperview()
            make.bottom.equalToSuperview().inset(30)
        }

        dayForecastStack.snp.makeConstraints { make in
            make.top.equalTo(collectionView.snp.bottom).offset(15)
            make.width.equalToSuperview()
            make.centerX.equalToSuperview()
            make.height.equalTo(181)
        }

        miscInfoView.snp.makeConstraints { make in
            make.top.equalTo(dayForecastStack.snp.bottom).offset(15)
            make.centerX.equalToSuperview()
            make.width.equalToSuperview()
            make.bottom.equalToSuperview()
        }
    }

    private func animateViews() {
        collectionView.fadeIn(duration: 1)
        firstSeparator.fadeIn(duration: 1)
        scrollView.fadeIn(duration: 1)
        secondSeparator.fadeIn(duration: 1)
    }

    private class func makeSeparator() -> UIView {
        let view = UIView()
        view.backgroundColor = .white.withAlphaComponent(0.5)
        view.alpha = 0
        return view
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = #colorLiteral(red: 0.2492019534, green: 0.5160208344, blue: 0.8688297868, alpha: 1)
        navigationItem.largeTitleDisplayMode = .never
        setupConstraints()
        loadData()
    }

    // MARK: - request data from DetailsInteractor

    private func loadData() {
        interactor?.loadForecast()
    }

    // MARK: - display view model from DetailsPresenter

    func displayDetailedForecast(viewModel: Details.ShowForecast.ViewModel) {
        dayForecastStack.setup(viewModels: viewModel.dailyForecastViewModels)
        miscInfoView.setup(viewModel: viewModel.miscInfoViewModel)
        collectionView.setup(with: viewModel.hourlyForecastViewModels)
        animateViews()
    }

    func displayCurrentWeather(viewModel: Details.ShowCurrentWeather.ViewModel) {
        topHeaderView.setup(viewModel: viewModel.headerViewModel)
    }
}
